namespace TypeFest.Net.SourceGenerator.SpecTests;

public class MapFromTests : TestBase
{
    [Fact]
    public async Task Works()
    {
        await RunAndCompareAsync("""
            using TypeFest.Net;

            namespace TestNamespace;

            [MapFrom<OtherPerson>()]
            public partial class Person
            {
                public string Name { get; set; }
            }
            
            public class OtherPerson
            {
                public string Name { get; set; }
            }
            """,
            """
            // <auto-generated/>
            namespace TestNamespace
            {
                partial class Person
                {
                    public static global::TestNamespace.Person FromOtherPerson(global::TestNamespace.OtherPerson value)
                    {
                        return new global::TestNamespace.Person
                        {
                            Name = value.Name,
                        };
                    }
                }
            }
            """
        );
    }
}
