namespace TypeFest.Net.SourceGenerator.SpecTests;

public class MapIntoTests : TestBase
{
    [Fact]
    public async Task Works()
    {
        await RunAndCompareAsync("""
            using TypeFest.Net;

            namespace TestNamespace;

            [MapInto<OtherPerson>()]
            public partial class Person
            {
                public string Name { get; set; }
            }
            
            public class OtherPerson
            {
                public string Name { get; set; }
            }
            """,
            """
            // <auto-generated/>
            namespace TestNamespace
            {
                partial class Person
                {
                    public global::TestNamespace.OtherPerson IntoOtherPerson()
                    {
                        return new global::TestNamespace.OtherPerson
                        {
                            Name = Name,
                        };
                    }
                }
            }
            """
        );
    }
}