using Microsoft.CodeAnalysis;

namespace TypeFest.Net.SourceGenerator.SpecTests;

public class PickTests : TestBase
{
    [Fact]
    public async Task SingleArg()
    {
        await RunAndCompareAsync("""
            using TypeFest.Net;

            namespace TestNamespace;

            [Pick<Person>("Name")]
            public partial class EditPerson;

            public class Person
            {
                public Guid Id { get; set; }
                public string Name { get; set; }
            }
            """,
            """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace
            {
                partial class EditPerson
                {
                    /// <inheritdoc cref="global::TestNamespace.Person.Name" />
                    public string Name { get; set; }
                }
            }
            """
        );
    }

    [Fact]
    public async Task MultiArg()
    {
        await RunAndCompareAsync("""
            using TypeFest.Net;

            namespace TestNamespace;

            [Pick<Person>("Name", "Age", "Occupation")]
            public partial class EditPerson;

            public class Person
            {
                public Guid Id { get; set; }
                public string Name { get; set; }
                public int Age { get; set; }
                public string Occupation { get; set; }
            }
            """,
            """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace
            {
                partial class EditPerson
                {
                    /// <inheritdoc cref="global::TestNamespace.Person.Name" />
                    public string Name { get; set; }
                    /// <inheritdoc cref="global::TestNamespace.Person.Age" />
                    public int Age { get; set; }
                    /// <inheritdoc cref="global::TestNamespace.Person.Occupation" />
                    public string Occupation { get; set; }
                }
            }
            """);
    }

    [Fact]
    public async Task ParamsAsArray()
    {
        await RunAndCompareAsync("""
            using TypeFest.Net;

            namespace TestNamespace;

            [Pick<Person>("Name", ["Age", "Occupation"])]
            public partial class EditPerson;

            public class Person
            {
                public Guid Id { get; set; }
                public string Name { get; set; }
                public int Age { get; set; }
                public string Occupation { get; set; }
            }
            """,
            """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace
            {
                partial class EditPerson
                {
                    /// <inheritdoc cref="global::TestNamespace.Person.Name" />
                    public string Name { get; set; }
                    /// <inheritdoc cref="global::TestNamespace.Person.Age" />
                    public int Age { get; set; }
                    /// <inheritdoc cref="global::TestNamespace.Person.Occupation" />
                    public string Occupation { get; set; }
                }
            }
            """);
    }

    [Fact]
    public async Task Enum()
    {
        await RunAndCompareAsync("""
            using TypeFest.Net;

            namespace TestNamespace;

            [Pick<Test>("One", "Two")]
            public partial enum PickTest;

            public enum Test
            {
                One,
                Two,
                Three,
            }
            """,
            """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace
            {
                partial enum PickTest
                {
                    /// <inheritdoc cref="global::TestNamespace.Test.One" />
                    One = 0,
                    /// <inheritdoc cref="global::TestNamespace.Test.Two" />
                    Two = 1,
                }
            }
            """);
    }

    [Fact]
    public async Task Record()
    {
        await RunAndCompareAsync("""
            using System;
            using TypeFest.Net;

            namespace TestNamespace;

            [Pick<Person>("Name", "Age")]
            public partial record EditPerson;

            public record Person(Guid Id, string Name, int Age);
            """,
            """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace
            {
                partial record EditPerson
                {
                    public EditPerson(string Name, int Age)
                    {
                        this.Name = Name;
                        this.Age = Age;
                    }

                    /// <inheritdoc cref="global::TestNamespace.Person.Name" />
                    public string Name { get; init; }
                    /// <inheritdoc cref="global::TestNamespace.Person.Age" />
                    public int Age { get; init; }
                }
            }
            """);
    }

    [Fact]
    public async Task RequiredProperty()
    {
        await RunAndCompareAsync("""
            using System;
            using TypeFest.Net;

            namespace TestNamespace;

            [Pick<Person>("Name")]
            public partial class EditPerson;

            public class Person
            {
                public required Guid Id { get; init; }
                public required string Name { get; init; }
            }
            """,
            """
            // <auto-generated/>
            #nullable enable

            namespace TestNamespace
            {
                partial class EditPerson
                {
                    /// <inheritdoc cref="global::TestNamespace.Person.Name" />
                    public required string Name { get; init; }
                }
            }
            """);
    }

    [Fact]
    public async Task InGlobalNamespace()
    {
        await RunAndCompareAsync("""
            using TypeFest.Net;
            public class Person
            {
                public string Name { get; set; }
            }

            [Pick<Person>("Name")]
            partial class EditPerson;
            """,
            // TODO: Do we are about the extra new line?
            """
            // <auto-generated/>
            #nullable enable

            partial class EditPerson
            {
                /// <inheritdoc cref="global::Person.Name" />
                public string Name { get; set; }
            }

            """
        );
    }

    [Fact]
    public async Task WithConstructor()
    {
        await RunAndCompareAsync("""
            using TypeFest.Net;

            namespace Test;

            public class Person
            {
                public Person(string name)
                {
                }

                public string Name { get; }
                public int Age { get; init; }
                public required string Occupation { get; init; }
            }

            [Pick<Person>("Name", "Age")]
            public partial class EditPerson;
            """,
            """
            // <auto-generated/>
            #nullable enable

            namespace Test
            {
                partial class EditPerson
                {
                    public EditPerson(string name)
                    {
                        Name = name;
                    }

                    /// <inheritdoc cref="global::Test.Person.Name" />
                    public string Name { get; }
                    /// <inheritdoc cref="global::Test.Person.Age" />
                    public int Age { get; init; }
                }
            }
            """
        );
    }
}