name: Release

on: 
  workflow_dispatch: {}

permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4

      - name: Pack
        run: dotnet pack

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push
        run: dotnet nuget push */**.nupkg --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source nuget
